.PHONY:build-maven
build-maven:
	dagger call java-build-by-maven --dir=../helper/dagger-maven export --path ${PWD}/../helper/out/dagger-maven.jar

.PHONY:build-gradle
build-gradle:
	dagger call java-build-by-gradle --dir=../helper/dagger-gradle export --path ${PWD}/../helper/out/dagger-gradle.jar
